#!/bin/bash

#SBATCH --partition=gpu_shared_course
#SBATCH --gres=gpu:0
#SBATCH --job-name=InstallAdditional
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=04:00:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_output_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

# activate the environment
source activate dl2022

# install additional packages
pip install ftfy regex tqdm
pip install git+https://github.com/openai/CLIP.git

# verify installation
python -c "import clip; print(f'CLIP available models: {clip.available_models()}')"